# fly.toml app configuration file generated for jon-love-portfolio on 2024-01-27T16:51:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jon-love-portfolio"
primary_region = "nrt"

[build]

[env]
  PORT = "3001" # add this

  [processes]
  app = 'run --allow-all ./main.ts'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
